spring:
  application:
    name: payment

  # Database
  datasource:
    url: jdbc:postgresql://localhost:30033/payment
    username: root
    password: a1234567!

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# PortOne API
portone:
  api:
    url: https://api.portone.io
    secret: Ww6s1RRhbQHgLsovpVZCVNmR0eF7dKUe30FVThYQknstaQAAvOsz9A8hAxHxUEXgq96CJgqjxcLuLdZX
  store:
    id: store-42931a45-dea7-4099-9727-a891d07e8310
